### ISSUE TITLE
Kanban board Set-up

### ISSUE THREAD

**Issue by Thoth1111** [HanaSabih/the-meal#21]
We are two partners in our team. 

We've set up a kanban board under the project tab of the repository. The board is copied from the JavaScript group capstone template using the instructions from the [copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects) repository and student c cards have been removed and their respective issues marked as closed.

The link to the project is: https://github.com/HanaSabih/the-meal/projects/2

**Comment by m05e5** [comment]
**Hi @Thoth1111  and @HanaSabih 

You did great. Your kanban board is complete!  There is nothing else to say other than... its time to start coding :shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights
✔️ Clean kanban board

## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**
